Boost Matheval: matheval::detail::math Namespace Reference
matheval::detail::math Namespace Reference
Functions
template<typename T >
T sgn (T x)
Sign function.
template<typename T >
T isnan (T x)
isnan function with adjusted return type
template<typename T >
T isinf (T x)
isinf function with adjusted return type
template<typename T >
T deg (T x)
Convert radians to degrees.
template<typename T >
T rad (T x)
Convert degrees to radians.
Function Documentation
template<typename T > T matheval::detail::math::deg (T x)
Convert radians to degrees.
Definition at line 82 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
template<typename T > T matheval::detail::math::isinf (T x)
isinf function with adjusted return type
Definition at line 78 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
template<typename T > T matheval::detail::math::isnan (T x)
isnan function with adjusted return type
Definition at line 74 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
template<typename T > T matheval::detail::math::rad (T x)
Convert degrees to radians.
Definition at line 86 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
template<typename T > T matheval::detail::math::sgn (T x)
Sign function.
Missing function in the STL. This calculates the mathematical sign function.
\[ \mathop{\mathrm{sgn}}(x) = \begin{cases} 1 & x > 0 \\ 0 & x = 0 \\ -1 & x < 0 \\ \end{cases} \]
Parameters
[in] x number
Returns
the sign of x
Definition at line 70 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().